### ISSUE TITLE
hddtemp show NaNº

### ISSUE THREAD

**Issue by varlesh** [kotelnik/plasma-applet-thermal-monitor#1]
Hello, very good widget!!! Thx ))
I'm start hddtemp as service, but them not working - show NaNº
Please, see screen (on panel):
![139](https://cloud.githubusercontent.com/assets/8083855/8175152/add66654-13ee-11e5-8e40-84eb19230332.png)
Tested on Kubuntu 15.04 KDE 5.3, with SSD Kingston V300 and HDD ST500LM012

**Comment by varlesh** [comment]
It seems problem is not Hddtemp. First sensor refuses show temperature. I'm add 3 widgets and see this:
![141](https://cloud.githubusercontent.com/assets/8083855/8175470/d4bbba44-13f3-11e5-9b28-95d001d018eb.png)

**Comment by kotelnik** [comment]
Thanks! Should be fixed now. Please try again.

**Comment by varlesh** [comment]
Thx, working :+1:
