### ISSUE TITLE
Feature request: custom font settings

### ISSUE THREAD

**Issue by BilyakA** [kotelnik/plasma-applet-thermal-monitor#10]
Hi there!
Since github doesn't provide any kind of feature request page I'll post it here.
It would be great to have custom font settings for applet to use. I like a lot your warning and meltdown icons so I maximized their size in applet (to make them more visible in system tray). But as temp text is not bold I can hardly see it over colored icon. So it would be great to have font settings for label and temp text to make them bold/italic or to change font (not only text size).

![Imgur](http://i.imgur.com/CCawsmL.png)
![Imgur](http://i.imgur.com/3gpJqW4.png)

Also a little issue easy to fix: warning and meltdown icons covers label text (see first pic above). I think it shouldn't.

P.S. don't be surprised with my CPU temperature. I am using Gentoo and I was compiling new Qt core in that moment on Core i7 ^_^

**Comment by kotelnik** [comment]
Yes, you're right, it doesn't look nice with the big icons under. So far I did the easy fix: label text is not covered by icon anymore. And I did another thing for readability - option for enabling drop shadows for label and temperature text. (latest git commit)

Of course I can still add the font options but I'll do that only if you still need it. So far it uses the default system-wide font...

RE: PS: I used to have gentoo, too :) So I remember the sleepless nights when compiling the whole KDE suite and other updates like firefox, chromium and stuff - it took ages... Then my fan started to be too lazy to manage so I switched to Arch :) But I still think it's one of the best distributions to have.

**Comment by BilyakA** [comment]
I'll try new build only tomorrow (it is almost midnight). Will make you know what I think. Thanks for fast fixes and for great applet!

**Comment by BilyakA** [comment]
Issue is closed. Thank you for fast fix!
Please remember to update kde-apps and kde-look applet to make it downloadable from plasma.

**Comment by kotelnik** [comment]
Sure, done :) np.
