### ISSUE TITLE
"Reload Temperature Sources" button resets text and icon settings

### ISSUE THREAD

**Issue by BilyakA** [kotelnik/plasma-applet-thermal-monitor#11]
Hello again, my friend :)

I've noticed strange behavior of "Reload Temperature Sources". It resets layout and all text and icons settings. I'll investigate this and provide you normal bag report. Also I am using github version 89de935 and not that one from kde-apps. Try reproducing it yourself, if you won't be able to - i'll give a try again this afternoon.

P.S. I am sorry not to found this problem during testing after last issue-fix.

**Comment by kotelnik** [comment]
Hi! :) That's absolutely OK, it would be probably unrelated to the change anyway.

I cannot reproduce this behaviour. If you are using the git version, did you remove the kde-apps applet from ~/.local/share/plasma/plasmoids/ so there is only one applet source code in the system?

**Comment by BilyakA** [comment]
@kotelnik Hi again!
I am very sorry for such a late response.
I can not reproduce this issue on latest build from kde-apps.
I guess I was my own installation issue or some problems related to previous installations.

**Comment by kotelnik** [comment]
I'm glad you resolved it :)
