### ISSUE TITLE
Setting a font size to the lowest setting has no effect

### ISSUE THREAD

**Issue by skwerlman** [kotelnik/plasma-applet-thermal-monitor#15]
If you decrease the font size of the alias, temperature, or icon to the lowest setting and hit apply, nothing happens. Setting the font size to any other setting works as expected.

I am using Thermal Monitor version 1.2.5 on Plasma 5.5.1

**Comment by kotelnik** [comment]
Hi, thanks for report! It should be fixed now.

**Comment by skwerlman** [comment]
It is indeed fixed. Thanks!
