### ISSUE TITLE
Only show temperature without the Alias

### ISSUE THREAD

**Issue by sudhirkhanger** [kotelnik/plasma-applet-thermal-monitor#27]
Hello,

I want to show one temperature in the panel, preferably the max, without any Alias. Alias doesn't have value to me when quickly checking the overall temperature.

Alias takes space and makes the whole widget look weird with it sitting on top corner and displacing temperature on the other side.

If only temperature could be shown, in vertical center, and alias be made optional that would be great.

Thanks.

**Comment by kotelnik** [comment]
Thanks for suggestion! It should now verticalCenter if no alias is set. Please reopen issue https://github.com/kotelnik/plasma-applet-thermal-monitor/issues/30 (duplicate) if necessary.
