### ISSUE TITLE
Can't find .plasmoid extension file

### ISSUE THREAD

**Issue by dhruvdutt** [kotelnik/plasma-applet-thermal-monitor#29]
There are only options for `.zip`, `AUR`, and `GitHub` in Plasma Widgets Library.
Also, when following the instructions from README.md file, make install fails.
> dhruvdutt@dhruvdutt:~/plasma-applet-thermal-monitor$ sudo make install
make: *** No rule to make target 'install'.  Stop.

System: Kubuntu 16.10 
KDE Plasma Version: 5.7.5
KDE Frameworks Version: 5.26.0
Kernel Version: 4.8.0-46-generic

**Comment by kotelnik** [comment]
Hi! I just updated README, it should now work. I also added proper plasmoid version to store.kde.org. It should now install no problem. Please reopen this if you'll have issues with installation.
