### ISSUE TITLE
Empty Resources list

### ISSUE THREAD

**Issue by fatino** [kotelnik/plasma-applet-thermal-monitor#3]
Hi I'm on arch. Installed from aur. lm_sensors installed but resources list is empty.
This is my sensors output http://pastebin.com/ydKziawS

**Comment by kotelnik** [comment]
Hi! That's weird. So when you open Thermal Monitor Settings... and in the first (Temperature) section under Resources table when you click on "+", the selectbox is entirely empty? If it is the case, please post somewhere log, which you get this way:
- open terminal
- killall plasmashell
- plasmashell &
Maybe there is a better way to aquire this log but currently I don't know about it...

**Comment by fatino** [comment]
Ahhh that's how it works. I thought I was meant to select from resource list.
You should change the behaviour so when nothing is added there is big + sign or something. 
Kinda misleading this way. No way to know I should press + button.

**Comment by kotelnik** [comment]
You're right, it isn't quite obvious when the list is empty... Thanks for bringing it up. Should be fixed now...

**Comment by fatino** [comment]
Slowly becoming your UI guy xd JK

**Comment by fatino** [comment]
00

**Comment by kotelnik** [comment]
Sure :-)
