### ISSUE TITLE
Center temperature if alias is not set

### ISSUE THREAD

**Issue by andreyorst** [kotelnik/plasma-applet-thermal-monitor#30]
I just need to see my temperature and i do not care about what core it is, so i just dot set the `alias`. But this looks awful: 
![image](https://user-images.githubusercontent.com/19470159/28753870-26185584-7543-11e7-8e42-a21d4ca10c3e.png)
It would be nucho more beautiful if temerature were centered vertically if alias don't set.
I can center it by increasing the font size, but this looks terrible too:
![image](https://user-images.githubusercontent.com/19470159/28753890-77590934-7543-11e7-9d65-0bc98fc3bdac.png)
And Even if alias is set it is hard to read it in a nor,al size panel which make it even more useless

**Comment by kotelnik** [comment]
Should now be in latest commits, thanks for suggestion :)! Please reopen if necessary.

**Comment by andreyorst** [comment]
Totally forgot to check. Well, maybe you misunderstood me, but I meant to center temperature should be centered vertically in the panel. No matter what font size do you use temperature still at the bottom.
I've installed it from git, to be sure.
![image](https://user-images.githubusercontent.com/19470159/32454644-e006cfbc-c330-11e7-8386-ce44711d770e.png)

and using slider to change the font size is kinda painful by the way
![image](https://user-images.githubusercontent.com/19470159/32454982-e8d9a726-c331-11e7-9e54-1a6cdf0100f6.png)
