### ISSUE TITLE
Patch of aticonfig support for ATI Catalyst driver

### ISSUE THREAD

**Issue by kergalym** [kotelnik/plasma-applet-thermal-monitor#31]
Hi!

I am user of ATI Catalyst driver for my graphic card HD 7870 Tahiti LE and I added aticonfig support to get temperature value. [Here is my patch](https://gist.github.com/kergalym/e7a54dac038225c14128bb2e028b36dc) for plasma-applet-thermal-monitor. 

You can reject the patch if you want, but I would be happy if you accept it. 
On the picture: RGPU is my graphic card.

![screenshot_20170718_190106](https://user-images.githubusercontent.com/9489149/28757301-424e3742-75a1-11e7-8b9b-8f11d88f23a1.png)

**Comment by kotelnik** [comment]
Thanks a lot for your contribution! Commited in master.
