### ISSUE TITLE
print spams journalctl

### ISSUE THREAD

**Issue by dkadioglu** [kotelnik/plasma-applet-thermal-monitor#35]
https://github.com/kotelnik/plasma-applet-thermal-monitor/blob/6055da34a5e23701bcfed3c8d92323df01c04cb9/package/contents/code/temperature-utils.js#L16

This line spams journalctl with one line of output according to the set update interval. Could you remove this please?

Thanks and best

**Comment by kotelnik** [comment]
Hi! Thanks for pointing that out :). It should now be fixed.
