### ISSUE TITLE
hddtemp and systemd

### ISSUE THREAD

**Issue by varlesh** [kotelnik/plasma-applet-thermal-monitor#5]
On Manjaro hddtemp sensor not avaiable on widget.
I run service with this manual, but problem not solved:
https://wiki.archlinux.org/index.php/Hddtemp#Daemon
![8](https://cloud.githubusercontent.com/assets/8083855/8894482/b50f9ae8-33c0-11e5-921e-42eefaa1a0cf.png)

**Comment by kotelnik** [comment]
Hi! Please give me output of this command:
netcat localhost 7634
(This command is called by the widget and its output is parsed.)

**Comment by varlesh** [comment]
Thx. I'm install gnu-netcat and hddtemp working.
