### ISSUE TITLE
HDD sources not properly initialized on plasma start

### ISSUE THREAD

**Issue by kotelnik** [kotelnik/plasma-applet-thermal-monitor#7]
Since Plasma upgraded to 5.4 HDD temp values are always at 0 when I reboot or logout/login or restart plasma shell. Then I have to remove HDD entries in Thermal Monitor settings and add them again, then it works fine. It's not something related to udisks2 change, it was like that with hdd-temp in previous version.

**Comment by kotelnik** [comment]
I was unable to replicate this bug, yet. But it seams "executable" datasource is not ready on startup and therefore it is not properly initialized at the time connectedSources are filled. I'll do more testing and get back here with more info...

**Comment by kotelnik** [comment]
Still unable to come up with something so I will need your (kajzer from aur:) help.

1)
While restarting plasma please see the plasma log - are there any messages containing "thermalMonitor"? Or you can just post me the whole log if you like.

2)
In the latest commit I've added "Reload Temperature Sources" action. This should skip the need for re-adding the HDD sources. When clicking this action I'd also like to see the plasma log.

Thank you!

**Comment by kajzersoze** [comment]
"Reload Temperature Sources" fixed it, thanks.
I'll post log soon.

**Comment by kajzersoze** [comment]
This is after login and HDD sources are at 0
http://pastebin.com/RfZwT6bh

and after "Reload Temperature Sources" :
http://pastebin.com/4tpVyrwX

**Comment by kotelnik** [comment]
Thanks for the logs. I can see the same output I have. Though my HDD temperature gets always updated after a while... I'll add more debug logging and get back to you.

**Comment by kotelnik** [comment]
I just did some minor adjustments and added more debug logging. Please give me the log after login again. And let the other temperatures update several times so I can see the updates in the log... Thanks!

**Comment by kajzersoze** [comment]
Maybe it's just me, maybe something went wrong during plasma upgrade from 5.3 to 5.4, I'm not sure.
Anyway, if you keep "Reload Temperature Sources" option in future versions all is good ! :)

**Comment by kotelnik** [comment]
Sure, that is the least I can do :)

**Comment by kotelnik** [comment]
Hi! I finally encountered the issue you were having and possibly fixed it with the latest commit. Please try if it is fixed for you, too. Thanks!

**Comment by kajzersoze** [comment]
Hi, sorry for late reply !
It's working fine now, cheers :)

**Comment by kotelnik** [comment]
Glad to hear that :)
