### ISSUE TITLE
HDD always zero

### ISSUE THREAD

**Issue by HeikoTietze** [kotelnik/plasma-applet-thermal-monitor#8]
Latest update does not show hdd temp at any time. I guess it's a different issue as what was solved by remove/add a sensor or reload data recently. The sensor is always 0.

Arch Linux
plasmashell 5.4.2
r33.2ea3dd6-1
udiskctl status lists both disks

**Comment by kotelnik** [comment]
I should test better, this slipped me out, thanks! I'll fix it with next update.

**Comment by kotelnik** [comment]
Should be fixed now.

**Comment by HeikoTietze** [comment]
Solved with r34.c16c797-1. Thanks a lot.
